Update Test

diff --git a/scripts/Test b/scripts/Test
--- a/scripts/Test
+++ b/scripts/Test
@@ -1,1 +1,75 @@
+#!/bin/bash
 
+# This script downloads the Enexis logo, wallpaper and support app icon and sets the wallpaper on the Mac.
+
+# Define the base directory
+BASE_DIR="/Library/Application Support/Enexis"
+
+# Define the target directories
+PICTURES_DIR="$BASE_DIR/Pictures"
+PACKAGES_DIR="$BASE_DIR/Packages"
+SCRIPTS_DIR="$BASE_DIR/Scripts"
+LOGS_DIR="$BASE_DIR/Logs"
+
+# Define the URL's to download the files
+LOGO_URL="https://enxp657sa01.blob.core.windows.net/enxp657ct01/pictures/Logo.png"
+WALLPAPER_URL="https://enxp657sa01.blob.core.windows.net/enxp657ct01/pictures/Wallpaper.jpg"
+SUPPORTAPPICON_URL="https://enxp657sa01.blob.core.windows.net/enxp657ct01/pictures/Supportappicon.png"
+
+# Define the target file path
+LOGO_FILE="$PICTURES_DIR/Logo.png"
+WALLPAPER_FILE="$PICTURES_DIR/Wallpaper.jpg"
+SUPPORTAPPICON_FILE="$PICTURES_DIR/Supportappicon.png"
+
+# Create the "Application Support" directory if it doesn't exist (optional, normally exists)
+if [ ! -d "/Library/Application Support/Enexis" ]; then
+    echo "Creating /Library/Application Support/Enexis directory"
+    sudo mkdir -p "/Library/Application Support/Enexis"
+fi
+
+# Create the base directory if it doesn't exist
+if [ ! -d "$BASE_DIR" ]; then
+    echo "Creating base directory: $BASE_DIR"
+    sudo mkdir -p "$BASE_DIR"
+fi
+
+# Create the target directories if they don't exist
+for DIR in "$PICTURES_DIR" "$PACKAGES_DIR" "$SCRIPTS_DIR" "$LOGS_DIR"; do
+    if [ ! -d "$DIR" ]; then
+        echo "Creating directory: $DIR"
+        sudo mkdir -p "$DIR"
+    fi
+done
+
+# Make the base directory hidden
+echo "Hiding the base directory: $BASE_DIR"
+sudo chflags hidden "$BASE_DIR"
+
+# Download logos to Pictures directory
+echo "Downloading logo's from $LOGO_URL to $LOGO_FILE"
+sudo curl -L -o "$LOGO_FILE" "$LOGO_URL"
+
+# Download wallpaper to Pictures directory
+echo "Downloading wallpaper from $WALLPAPER_URL to $WALLPAPER_FILE"
+sudo curl -L -o "$WALLPAPER_FILE" "$WALLPAPER_URL"
+
+# Download Support app icon to Pictures directory
+echo "Downloading Support app icon from $SUPPORTAPPICON_URL to $SUPPORTAPPICON_FILE"
+sudo curl -L -o "$SUPPORTAPPICON_FILE" "$SUPPORTAPPICON_URL"
+
+# Check if download was successful
+if [ $? -eq 0 ]; then
+    echo "Files downloaded successfully to $PICTURES_DIR"
+else
+    echo "Failed to download files"
+    exit 1
+fi
+
+# Get the currently logged-in user
+#USER=$(stat -f%Su /dev/console)
+
+# Set wallpaper via desktoppr
+echo "Setting wallpaper using $WALLPAPER_FILE"
+
+# Voer desktoppr uit met de opgegeven URL
+desktoppr "$WALLPAPER_URL"
